const constants={
    EDIT_INPUT:"EDIT_INPUT",
    RESET_INPUT:"RESET_INPUT",
    ADD_LIST:"ADD_LIST",
    CHECK_TOGGLE_LIST:"CHECK_TOGGLE_LIST",
    EDIT_LIST:"EDIT_LIST",
    REMOVE_LIST:"REMOVE_LIST",
    REALIGN_LIST:"REALIGN_LIST",

    ADD_STATE:"ADD_STATE", //리스트 글쓰기모드
    EDIT_STATE:"EDIT_STATE", //리스트 편집모드

    REALIGN_MODE:"REALIGN_MODE", 
    REALIGN_GET_FID:"REALIGN_GET_FID",
    REALIGN_FID_RESET: "REALIGN_FID_RESET",
    
    LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
    LOG_IN_FAILURE: "LOG_IN_FAILURE",
    LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
    GET_TODO_LIST: "GET_TODO_LIST",
    PUT_TODO_SUCCESS: "PUT_TODO_SUCCESS",
    PUT_TODO_FAILURE: "PUT_TODO_FAILURE",

    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE"
}

export default constants;